const CONFIGDATA = {
  titleHeader: "ZAMA SHA SAMAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  descriptionHeader:
    "They say some people worth melting I melt for you SAMAHA",
  buttonYes: "Yes",
  buttonNo: "No",
  titleModar: "Thank you !!",
  descriptionModar:
    "URO BA HUM DARLA AOGHAGAMA ISTRI BA HUM DARLA KOMA  KOR BA HUM ZA SAFA KOMA ROTAI BA HUM DARTA ACHOMA ROTAI BA HUM DARTA PAKHOMA KHER DE BAS DE PAKHLE CHAL NA RAZE BUT AHA BAM EZDA KAMA KA STA ZRA WE ",
};
